class Sun extends Entity {
    // If targetY is provided, it's generated by a sunflower. 
    // If not, it falls from the sky to a random targetY.
    constructor(game, x, y, targetY = null) {
        super(game, x, y);
        this.value = 25;
        this.radius = 25;
        this.speed = 50; // Fall speed
        
        if (targetY === null) {
            // Falls from sky
            this.targetY = game.board.offsetY + Math.random() * (game.board.rows * game.board.cellHeight - 50);
        } else {
            this.targetY = targetY;
            // Arc movement for sunflower suns (simplified as direct move for MVP)
        }
        
        this.state = 'FALLING'; // FALLING, GROUND, COLLECTED
        this.lifeTime = 0;
        this.maxLife = 10; // Disappears after 10 seconds on ground
    }
    
    update(deltaTime) {
        if (this.state === 'FALLING') {
            this.y += this.speed * deltaTime;
            if (this.y >= this.targetY) {
                this.y = this.targetY;
                this.state = 'GROUND';
            }
        } 
        else if (this.state === 'GROUND') {
            this.lifeTime += deltaTime;
            if (this.lifeTime >= this.maxLife) {
                this.isDead = true;
            }
        }
        else if (this.state === 'COLLECTED') {
            // Move towards top-left corner (Sun Bank)
            const dx = 50 - this.x;
            const dy = 30 - this.y;
            const dist = Math.hypot(dx, dy);
            
            if (dist < 10) {
                this.isDead = true;
                this.game.addSun(this.value);
            } else {
                const moveSpeed = 500 * deltaTime;
                this.x += (dx / dist) * moveSpeed;
                this.y += (dy / dist) * moveSpeed;
            }
        }
    }
    
    collect() {
        if (this.state !== 'COLLECTED') {
            this.state = 'COLLECTED';
        }
    }
    
    draw(ctx) {
        ctx.save();
        ctx.translate(this.x, this.y);
        
        // Spin animation
        ctx.rotate(Date.now() / 1000);
        
        // Sun rays
        ctx.fillStyle = '#FFA500';
        ctx.beginPath();
        for (let i = 0; i < 8; i++) {
            ctx.moveTo(0, 0);
            ctx.lineTo(25, -5);
            ctx.lineTo(25, 5);
            ctx.rotate(Math.PI / 4);
        }
        ctx.fill();
        
        // Sun center
        ctx.fillStyle = '#FFFF00';
        ctx.beginPath();
        ctx.arc(0, 0, 18, 0, Math.PI * 2);
        ctx.fill();
        ctx.strokeStyle = '#DAA520';
        ctx.lineWidth = 2;
        ctx.stroke();
        
        ctx.restore();
    }
}
